### ISSUE TITLE
Responsiveness for Landing Page

### ISSUE THREAD

**Issue by Matt-Vance** [projectunic0rn/travel-map-ui#77]
Document issue details: 

Mobile/Tablet: 
-Login needs more margin-top
-Login form could be centered vertically

**Comment by hoangviet1993** [comment]
> Login needs more margin-top

Would moving the close button to the same line with the "Login or Signup" line help with this?
E.g:
![Screen Shot 2020-03-16 at 4 30 06 PM](https://user-images.githubusercontent.com/11153258/76807970-70526680-67a3-11ea-84bb-303ced8931c0.png)

> -Login form could be centered vertically

Are you thinking about a popup with the Signin form centered ala Tap cities popup?

**Comment by GreenWithMV** [comment]
Are you thinking about a popup with the Signin form centered ala Tap cities popup? -- I think this is OK not being centered on desktop. On mobile I believe it is centered but if it is not then it should be
I am OK with the current design where the login form is optional.
I would like the Login form to disappear once the hamburger icon appears though since with smaller view-width, I would like more real estate dedicated to the website and only show login form on request. -- Agreed, that is a good change

**Comment by GreenWithMV** [comment]
![IMG_1389](https://user-images.githubusercontent.com/46555800/76884570-2321d380-683b-11ea-8022-3e7acb9739fa.PNG)
![IMG_1388](https://user-images.githubusercontent.com/46555800/76884577-24eb9700-683b-11ea-9aff-46984ea8fbc3.PNG)

**Comment by GreenWithMV** [comment]
So basically the login in the menu (when you hit the hamburger icon) needs move vertical spacing/line height. And then for mobile the login/signup form needs to be centered (horizontally centered, vertical needs to account for the header so that it does not cover that up)

**Comment by hoangviet1993** [comment]
@GreenWithMV Are we all done with this issue?
